CREATE TABLE tutores (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    CONSTRAINT uk_tutores_email UNIQUE (email)
);

COMMENT ON TABLE tutores IS 'Responsável legal pelos pets; dono do cadastro na plataforma.';
COMMENT ON COLUMN tutores.id IS 'Identificador único do tutor.';
COMMENT ON COLUMN tutores.nome IS 'Nome completo do tutor.';
COMMENT ON COLUMN tutores.email IS 'E-mail do tutor, único — também usado como login em usuarios.email.';
COMMENT ON COLUMN tutores.telefone IS 'Telefone de contato (opcional).';

CREATE TABLE usuarios (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    role       VARCHAR(20) NOT NULL,
    tutor_id   BIGINT,
    criado_em  TIMESTAMP NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_tutor_id UNIQUE (tutor_id),
    CONSTRAINT fk_usuarios_tutor FOREIGN KEY (tutor_id) REFERENCES tutores (id) ON DELETE CASCADE,
    CONSTRAINT ck_usuarios_role CHECK (role IN ('TUTOR', 'VETERINARIO'))
);

COMMENT ON TABLE usuarios IS 'Identidade autenticada da API (login/JWT). TUTOR é 1:1 com tutores; VETERINARIO não tem tutor associado.';
COMMENT ON COLUMN usuarios.id IS 'Identificador único do usuário.';
COMMENT ON COLUMN usuarios.email IS 'E-mail de login, único.';
COMMENT ON COLUMN usuarios.senha_hash IS 'Hash BCrypt da senha — nunca texto puro.';
COMMENT ON COLUMN usuarios.role IS 'Perfil de acesso: TUTOR ou VETERINARIO.';
COMMENT ON COLUMN usuarios.tutor_id IS 'FK opcional para tutores; obrigatória e única quando role = TUTOR.';
COMMENT ON COLUMN usuarios.criado_em IS 'Data/hora de criação da conta.';

CREATE TABLE pets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome              VARCHAR(255) NOT NULL,
    especie           VARCHAR(100) NOT NULL,
    raca              VARCHAR(100),
    idade             INTEGER,
    peso              DOUBLE PRECISION,
    observacoes_saude TEXT,
    tutor_id          BIGINT NOT NULL,
    CONSTRAINT fk_pets_tutor FOREIGN KEY (tutor_id) REFERENCES tutores (id)
);

CREATE INDEX idx_pets_tutor_id ON pets (tutor_id);

COMMENT ON TABLE pets IS 'Pet cadastrado por um tutor, com dados clínicos básicos. Núcleo da aplicação — CRUD 1 avaliado na Sprint DevOps.';
COMMENT ON COLUMN pets.id IS 'Identificador único do pet.';
COMMENT ON COLUMN pets.nome IS 'Nome do pet.';
COMMENT ON COLUMN pets.especie IS 'Espécie (ex.: Cachorro, Gato, Peixe).';
COMMENT ON COLUMN pets.raca IS 'Raça do pet (opcional).';
COMMENT ON COLUMN pets.idade IS 'Idade em anos (opcional).';
COMMENT ON COLUMN pets.peso IS 'Peso em quilogramas (opcional).';
COMMENT ON COLUMN pets.observacoes_saude IS 'Observações clínicas livres (alergias, condições, etc.).';
COMMENT ON COLUMN pets.tutor_id IS 'FK para tutores — dono do pet; nunca alterável pelo cliente, sempre resolvido pelo token JWT.';

CREATE TABLE consultas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data          DATE NOT NULL,
    horario       TIME,
    tipo_consulta VARCHAR(150) NOT NULL,
    status        VARCHAR(20) NOT NULL,
    observacoes   TEXT,
    pet_id        BIGINT NOT NULL,
    CONSTRAINT fk_consultas_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT ck_consultas_status CHECK (status IN ('AGENDADA', 'REALIZADA', 'CANCELADA'))
);

CREATE INDEX idx_consultas_pet_id ON consultas (pet_id);
CREATE INDEX idx_consultas_status ON consultas (status);
CREATE INDEX idx_consultas_data ON consultas (data);

COMMENT ON TABLE consultas IS 'Consulta veterinária agendada/realizada/cancelada para um pet. Núcleo da aplicação — CRUD 2 avaliado na Sprint DevOps. Relaciona-se com pets (N:1).';
COMMENT ON COLUMN consultas.id IS 'Identificador único da consulta.';
COMMENT ON COLUMN consultas.data IS 'Data da consulta.';
COMMENT ON COLUMN consultas.horario IS 'Horário da consulta (usado junto com a data para checar disponibilidade em consulta_slots).';
COMMENT ON COLUMN consultas.tipo_consulta IS 'Tipo/motivo da consulta (ex.: Vacinação, Rotina, Retorno).';
COMMENT ON COLUMN consultas.status IS 'Situação atual: AGENDADA, REALIZADA ou CANCELADA.';
COMMENT ON COLUMN consultas.observacoes IS 'Observações clínicas do atendimento (opcional).';
COMMENT ON COLUMN consultas.pet_id IS 'FK para pets — pet atendido nesta consulta.';

CREATE TABLE consulta_slots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data        DATE NOT NULL,
    horario     TIME NOT NULL,
    consulta_id BIGINT NOT NULL,
    CONSTRAINT uk_consulta_slots_data_horario UNIQUE (data, horario),
    CONSTRAINT uk_consulta_slots_consulta UNIQUE (consulta_id),
    CONSTRAINT fk_consulta_slots_consulta FOREIGN KEY (consulta_id) REFERENCES consultas (id) ON DELETE CASCADE
);

COMMENT ON TABLE consulta_slots IS 'Reserva de horário (data+hora) de uma consulta AGENDADA. A UNIQUE(data,horario) garante, no próprio banco, que dois agendamentos concorrentes nunca ocupem o mesmo horário.';
COMMENT ON COLUMN consulta_slots.consulta_id IS 'FK 1:1 para a consulta dona do slot; removida em cascata quando a consulta é excluída.';

CREATE TABLE lembretes (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo                   VARCHAR(255) NOT NULL,
    descricao                TEXT,
    data_lembrete            DATE NOT NULL,
    tipo                     VARCHAR(100) NOT NULL,
    status                   VARCHAR(20) NOT NULL,
    pet_id                   BIGINT NOT NULL,
    recorrencia_dias         INTEGER,
    data_conclusao           DATE,
    criado_por_usuario_id    BIGINT,
    concluido_por_usuario_id BIGINT,
    origem_lembrete_id       BIGINT,
    CONSTRAINT fk_lembretes_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT ck_lembretes_status CHECK (status IN ('PENDENTE', 'CONCLUIDO', 'CANCELADO')),
    CONSTRAINT fk_lembretes_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_lembretes_concluido_por FOREIGN KEY (concluido_por_usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_lembretes_origem FOREIGN KEY (origem_lembrete_id) REFERENCES lembretes (id)
);

CREATE INDEX idx_lembretes_pet_id ON lembretes (pet_id);
CREATE INDEX idx_lembretes_status ON lembretes (status);

COMMENT ON TABLE lembretes IS 'Cuidado preventivo definido pelo veterinário para um pet, com recorrência opcional. Suporte ao fluxo de negócio além do CRUD.';
COMMENT ON COLUMN lembretes.recorrencia_dias IS 'Se preenchido, ao concluir o lembrete uma nova ocorrência é criada automaticamente N dias depois.';
COMMENT ON COLUMN lembretes.data_conclusao IS 'Data em que o tutor confirmou a execução do cuidado.';
COMMENT ON COLUMN lembretes.criado_por_usuario_id IS 'FK para usuarios — veterinário que definiu o cuidado.';
COMMENT ON COLUMN lembretes.concluido_por_usuario_id IS 'FK para usuarios — tutor que confirmou a execução.';
COMMENT ON COLUMN lembretes.origem_lembrete_id IS 'Auto-referência: aponta para o lembrete que originou esta ocorrência recorrente.';

CREATE TABLE interacoes_ia (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta  TEXT NOT NULL,
    resposta  TEXT NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    categoria VARCHAR(100),
    pet_id    BIGINT NOT NULL,
    CONSTRAINT fk_interacoes_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_interacoes_pet_id ON interacoes_ia (pet_id);

COMMENT ON TABLE interacoes_ia IS 'Histórico de perguntas e respostas do assistente de orientação de saúde animal, vinculado a um pet.';
COMMENT ON COLUMN interacoes_ia.pergunta IS 'Pergunta enviada pelo tutor.';
COMMENT ON COLUMN interacoes_ia.resposta IS 'Resposta gerada para orientação (histórico persistido).';
COMMENT ON COLUMN interacoes_ia.categoria IS 'Categoria da pergunta (ex.: Alimentação, Vacinação, Sintomas).';
