CREATE TABLE tutores (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    telefone  VARCHAR(50),
    CONSTRAINT uk_tutores_email UNIQUE (email)
);

CREATE TABLE pets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(255) NOT NULL,
    especie             VARCHAR(100) NOT NULL,
    raca                VARCHAR(100),
    idade               INTEGER,
    peso                DOUBLE PRECISION,
    observacoes_saude   TEXT,
    tutor_id            BIGINT NOT NULL,
    CONSTRAINT fk_pets_tutor FOREIGN KEY (tutor_id) REFERENCES tutores (id)
);

CREATE INDEX idx_pets_tutor_id ON pets (tutor_id);

CREATE TABLE consultas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data           DATE NOT NULL,
    horario        TIME,
    tipo_consulta  VARCHAR(150) NOT NULL,
    status         VARCHAR(20) NOT NULL,
    observacoes    TEXT,
    pet_id         BIGINT NOT NULL,
    CONSTRAINT fk_consultas_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT ck_consultas_status CHECK (status IN ('AGENDADA', 'REALIZADA', 'CANCELADA'))
);

CREATE INDEX idx_consultas_pet_id ON consultas (pet_id);
CREATE INDEX idx_consultas_status ON consultas (status);
CREATE INDEX idx_consultas_data ON consultas (data);

CREATE TABLE lembretes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo         VARCHAR(255) NOT NULL,
    descricao      TEXT,
    data_lembrete  DATE NOT NULL,
    tipo           VARCHAR(100) NOT NULL,
    status         VARCHAR(20) NOT NULL,
    pet_id         BIGINT NOT NULL,
    CONSTRAINT fk_lembretes_pet FOREIGN KEY (pet_id) REFERENCES pets (id),
    CONSTRAINT ck_lembretes_status CHECK (status IN ('PENDENTE', 'CONCLUIDO', 'CANCELADO'))
);

CREATE INDEX idx_lembretes_pet_id ON lembretes (pet_id);
CREATE INDEX idx_lembretes_status ON lembretes (status);

CREATE TABLE interacoes_ia (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pergunta   TEXT NOT NULL,
    resposta   TEXT NOT NULL,
    data_hora  TIMESTAMP NOT NULL,
    categoria  VARCHAR(100),
    pet_id     BIGINT NOT NULL,
    CONSTRAINT fk_interacoes_pet FOREIGN KEY (pet_id) REFERENCES pets (id)
);

CREATE INDEX idx_interacoes_pet_id ON interacoes_ia (pet_id);
