CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(150) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    senha_hash  VARCHAR(255) NOT NULL,
    role        VARCHAR(20) NOT NULL,
    tutor_id    BIGINT,
    criado_em   TIMESTAMP NOT NULL,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_tutor_id UNIQUE (tutor_id),
    CONSTRAINT fk_usuarios_tutor FOREIGN KEY (tutor_id) REFERENCES tutores (id) ON DELETE CASCADE,
    CONSTRAINT ck_usuarios_role CHECK (role IN ('TUTOR', 'VETERINARIO'))
);

CREATE TABLE consulta_slots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data        DATE NOT NULL,
    horario     TIME NOT NULL,
    consulta_id BIGINT NOT NULL,
    CONSTRAINT uk_consulta_slots_data_horario UNIQUE (data, horario),
    CONSTRAINT uk_consulta_slots_consulta UNIQUE (consulta_id),
    CONSTRAINT fk_consulta_slots_consulta FOREIGN KEY (consulta_id) REFERENCES consultas (id) ON DELETE CASCADE
);

ALTER TABLE lembretes ADD COLUMN recorrencia_dias INTEGER;
ALTER TABLE lembretes ADD COLUMN data_conclusao DATE;
ALTER TABLE lembretes ADD COLUMN criado_por_usuario_id BIGINT;
ALTER TABLE lembretes ADD COLUMN concluido_por_usuario_id BIGINT;
ALTER TABLE lembretes ADD COLUMN origem_lembrete_id BIGINT;

ALTER TABLE lembretes ADD CONSTRAINT fk_lembretes_criado_por FOREIGN KEY (criado_por_usuario_id) REFERENCES usuarios (id);
ALTER TABLE lembretes ADD CONSTRAINT fk_lembretes_concluido_por FOREIGN KEY (concluido_por_usuario_id) REFERENCES usuarios (id);
ALTER TABLE lembretes ADD CONSTRAINT fk_lembretes_origem FOREIGN KEY (origem_lembrete_id) REFERENCES lembretes (id);
